### PR TITLE
add inadequate test

### PR DESCRIPTION
**Pull request by jinjagit**
see last (only) commit to this branch... created inadequate test of def containing conditional loop

how do I mock a series of invalid user inputs, followed by a valid user input to a loop within a method, and also test the correct result is given by each loop, which in this case would be printing (different) error messages, then finally returning the last mocked user input?

### CODE REVIEW

**Comment by oliverbarnes** [comment]
At first quick read, I'm having a hard time understanding what you're trying to do. This is also due, of course, to my not being familiar with the project :) I could spend some time looking at the exercise, cloning your repo and playing with it to get it, but ideally the repo and the PR specially should have enough info for a reviewer to comment just based on the code. 

One thing that would be great here is if you added a screen recording demonstrating what the game does in the README (as a separate PR), and another short recording showing what you're trying to test exactly, here in this PR.

good documentation and expressive PRs being important skills (that a lot of experienced devs lack, actually), so this would be a good exercise as well

**Comment by jinjagit** [comment]
sure, I can do that, but for the purposes of my question (in the pull req)
I am just trying to test a loop that gets a user input from the terminal,
and loops back to prompting for another input (with error message) until
user inputs correct type of input (integer between 1 and 7). I have no idea
how to test that loop, with a series of 'mock' incorrect user inputs,
followed by an eventual correct input.

**Comment by jinjagit** [comment]
I can test the method that tests the input and fires off an error message
or returns an OK input... since even though it is called within a loop, it
is separate and has inputs and outputs that can be tested easily... I'm
just interested in how to test methods with loops, especially conditional
loops (until <condition> do, for example)

**Comment by jinjagit** [comment]
More clarity: This in a RSpec question... the app is trivial and I would
have no problem finishing it without writing tests... i am just trying to
practice TDD

**Comment by oliverbarnes** [comment]
I know you're trying to figure out how to test _something_, but then the description just looses me because I lack context and don't want to spend the time playing with it. get used to making the life of the reviewer easy! 🎥

(we could pair on it, but I'm still busy with my work and other brazil stuff. the video will help me help you and also be a good exercise)

**Comment by jinjagit** [comment]
Yeah, don't worry... I'll finish the app, make sure the readme explains it
all (possibly with video) and see if I can find a way to test it after.
BUT, I can explain really simply in pseudocode :-)

Consider this code:

input = nil
until input >= 0 && input <= 5 do
  input = gets.chomp
end

What's the RSPEC to:
create 'mock' multiple user inputs (to gets.chomp), starting with those
that DON'T meet the condition (in this case, just integers outside of
range, for example, and with a final input that DOES meet the condition?

My problem arises from the fact that the 'input' is not a value passed into
the code as an argument, though yes I can make the 'conditional check' a
separate method with an input argument and test that (and I have).

**Comment by oliverbarnes** [comment]
The point I'm trying to make is about pull requests and collaboration, way more important than the rspec problem at hand.

For one thing, you'll very rarely deal with command line scripts on your day to day work, while pull requests are a fundamental everyday thing, and doing them well is a big differential when getting hired.

On open source projects it's even more so, you'll loose good will very quickly if you don't change your PRs as requested by reviewers, who usually have very limited time to spare and loads of PRs to review - they might even be ignored. Pull request reviews can be brutal in all sorts of different ways. So I'm trying to get you into the flow from the beginning.

But I know you're just getting acquainted with them :) so ok, let's skip the video. I understand the problem better now, the pseudo code helps - though having more context as for the code would be good, I'll have to look at the remainder of the codebase, which I should anyway as part of the larger review.

I don't do much command line scripting, so I don't have a clear answer right off the bat - I think I'd try stubbing `gets.chomp` and making it return different values as you suggested. Play with the script some more, see if you've covered most scenarios. And yes, decouple the validation of the input as separate thing on itself

**Comment by jinjagit** [comment]
Yeah, I get what you're trying to teach me, and it's appreciated
(especially since I have done zero collaborative work)  it's just probably
not a very realistic issue for a pull request, since the code works and
really I am asking a specific question about RSpec, hence I thought a
screenshare would be easiest... I explain, and you help me write an RSpec
test ;-)

No worries, though, I can also investigate stubbing after I finish the app.

Should finish the app tomorrow, then will make the readme super clear, and
it will be easier for you to see what it does, etc. (Though that won't
really help with the RSpec question)

**Comment by jinjagit** [comment]
Meanwhile the Pro Git book <https://git-scm.com/book/en/v2/> I'm reading
(free online version) is very good... handy for your mentoring maybe?

**Comment by oliverbarnes** [comment]
A screenshare would be easiest, but recording and then getting feedback is
the second best option when an exchange in writing is going slow.

About the issue “not being worth a pull request”, get used to the idea of
pull requests even for small typos in READMEs. Out there any tiny change
comes in PR, if you want it reviewed.

**Comment by oliverbarnes** [comment]
Yeah, Pro Git is one of the big references. Good that you’re reading it

**Pull request merged**
