### PR TITLE
Game win

### PR DESCRIPTION
**Pull request by jinjagit**
I have updated [ReadMe](https://github.com/jinjagit/connect_four/tree/game-win) to include:
1. Explanation of app (with screenshots)
2. Code organization
3. RSpec tests

The problems I am having with writing specific tests are briefly explained at the end of the RSpec section (bottom of [ReadMe](https://github.com/jinjagit/connect_four/tree/game-win)).

No need for response. I am just updating you before our screen-share (not urgent). Cheers!

### CODE REVIEW

**Review by oliverbarnes — APPROVED** [review]
The readme is great, and the comments above the methods are helpful too 👌 I'm going to go ahead and merge this for you to keep moving. A few notes for the future:

- it's better to separate PRs into discrete sets of changes. This one might be broken down into one for readme updates describing how the game and code work, and another for code changes. The method comments might fit into the first one, given it's documentation as well
- I think you've been adding the pull request description as comments, rather than using the description field that's there for it. 
- you can add me as a reviewer for a PR, and I'll be notified of it (no need to send me a manual email)
- reviewers usually merge PRs once they've approved the changes

**Comment by jinjagit** [comment]
Cool, I'll try to remember those (super useful real world) tips :-)

Thanks for taking the time to review and give feedback!

Abx!

**Comment by oliverbarnes** [comment]
a couple of other notes:

- commit history is something that's good to be as clean as possible, for later reference by you or other programmers. repeated `updated readme` commits can be [squashed](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_squashing) into one
- Pull request history is also used as future reference - so "Game win" is probably not a very descriptive pull request title

**Comment by jinjagit** [comment]
Yeah, just finished a lot of reading around git, so a lot of this is new to
me.

Had already decided to try to use branches to manage my extremely atomic
commit habit (which I think is fundamentally sound, but not necessary to
reveal to the world).

Next step I was planning was to have a 'dev' branch, which I periodically
merge back into master (after adding a feature, for example), then branch
again off 'dev' to add feature / work on readme, etc, but use rebase to add
such work back into 'dev' when ready.

Or something like that. basically I need to sart doing this stuff to learn
how to (and how not to) do it.

**Comment by oliverbarnes** [comment]
I know it's all new to you, of course. my comments are meant to point new
things to be aware of, and not as "you fucked up" corrections.

but pull request reviews can definitely feel like that, no matter what the
tone. It's one of the toughest parts of the job (both being reviewed and
reviewing), to me. Good to develop some detachment

Adding intermediary `dev` branch seems like over-complicating at this
point. But it's sometimes useful in big projects with big teams

**Comment by jinjagit** [comment]
Don't worry, I didn't take your comments in that tone at any point :-)

**Comment by oliverbarnes** [comment]
good :) hopefully I'm getting better at my reviewing

**Pull request merged**
